<a href="https://colab.research.google.com/github/Athitiya00/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np        # package สำหรับทำงานกับข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ matrix)

# Numpy array

## สร้าง numpy array

In [2]:
np_a = np.array([[1,2,3],[4,5,6]])     # สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

## matrix transpose

In [6]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## สร้าง matrix เริ่มต้น (zeros, ones)

In [7]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง matrix random

In [10]:
np.random.randn(5,5)     #random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[-0.88273696, -0.85037083, -0.13908353,  1.13693174,  0.20803028],
       [-0.60879294, -0.66214839,  0.0966342 , -0.44931892,  0.79365661],
       [ 0.2699609 , -1.07634613,  0.14348203,  0.11900443, -0.19993552],
       [ 0.94409801,  0.42596892, -0.85183176, -1.84910512, -0.40594871],
       [ 0.38161064,  1.013914  ,  0.58068785, -1.44576329,  0.14515972]])

In [11]:
2*(5*np.random.randn(3,3))     #random เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[  2.78923031,   0.14903717,   4.04700159],
       [  5.18330216, -17.51320179,  21.62090164],
       [ 19.83303923,  -9.0808084 ,  -1.67303394]])

In [12]:
np.random.randint(5,11,(4,5))     # random เลขจำนวนเต็ม ระหว่าง (5,11) ขนาด (4x5)

array([[ 9,  8,  6, 10, 10],
       [10,  5,  6,  6,  5],
       [10,  9,  9,  7, 10],
       [ 5,  9,  6,  6, 10]])