<a href="https://colab.research.google.com/github/Athitiya00/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import numpy as np        # package สำหรับทำงานกับข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ matrix)

# Numpy array

## สร้าง numpy array

In [54]:
np_a = np.array([[1,2,3],[4,5,6]])     # สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [55]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
np_a.shape

(2, 3)

In [57]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

## matrix transpose

In [58]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## สร้าง matrix เริ่มต้น (zeros, ones)

In [59]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [60]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [61]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าง matrix random

In [62]:
np.random.randn(5,5)     #random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[-0.22831612, -0.30122928, -0.46948557, -0.30421199,  0.85119692],
       [-1.65841294, -0.49914723, -0.95220414, -0.14233773, -0.46659542],
       [-1.31333136, -2.31172088, -1.22551525,  0.02649095, -0.87221813],
       [-1.94114923, -0.50691157,  0.2028022 , -0.72733835,  0.41135515],
       [-1.57437845, -1.64089736,  1.0828406 ,  1.02992285,  1.52374189]])

In [63]:
2*(5*np.random.randn(3,3))     #random เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[ 10.32609943, -10.35943952,   7.03756308],
       [ -4.28366319,  -8.19187883, -20.41583817],
       [  7.96616388,  -4.50258908,  11.38190565]])

In [64]:
np.random.randint(5,11,(4,5))     # random เลขจำนวนเต็ม ระหว่าง (5,11) ขนาด (4x5)

array([[10, 10,  5,  5,  9],
       [ 8,  7,  8, 10, 10],
       [10, 10,  8,  5,  5],
       [ 5, 10,  9,  9,  8]])

## matix properties

In [65]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
np_a.T #transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
1+np_a #add scalar to matix บวก

array([[2, 3, 4],
       [5, 6, 7]])

In [68]:
2*np_a #muliply scalar to matrix คูณ

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [69]:
np_c = np.array([[6,5,4],[3,2,1]])

In [70]:
np_a+np_c #adding matix to matix

array([[7, 7, 7],
       [7, 7, 7]])

In [71]:
np_a.shape

(2, 3)

In [72]:
np_c.shape

(2, 3)

In [73]:
np_c.T.shape

(3, 2)

In [74]:
np.dot(np_a,np_c.T) # multipling matrix to matix (a,b) x (b,c) =(a,c) คูณเมทริคกับเมทริค

array([[28, 10],
       [73, 28]])

## Indexing&Slicing

In [75]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
np_a[1,1]#ชี้

5

In [77]:
np_a[:2,:2] #ตัด สไลด์ เอาตัวแรกถึงตัวที่2ข้างหลังไม่เอา

array([[1, 2],
       [4, 5]])

In [78]:
np_a[0,:]

array([1, 2, 3])

## Useful functions

In [79]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
np.sum(np_a)#บวกทุกตัวในนั้น

21

In [81]:
np.sum(np_a,axis=0)#ค่าในแนวนอนทั้งหมดมารวมกัน #axis=0 ก็คือรวมเลขในแต่ละแถว

array([5, 7, 9])

In [82]:
np.sum(np_a,axis=1)#ค่าในแนวตั้งทั้งหมดมารวมกัน #axis=0 ก็คือรวมเลขในแต่ละหลัก

array([ 6, 15])

In [83]:
np.mean(np_a)#ดูค่ามีน

3.5

In [84]:
np.mean(np_a,axis=0)#หามีนของแต่ละคอลัมน์

array([2.5, 3.5, 4.5])

### วนลูปเอง

####summatiom รวมค่าทุกค่าในarray

In [85]:
np_a.shape

(2, 3)

```np.sum(np_a)```

In [86]:
sum_all = 0

for row in range(np_a.shape[0]):
     for col in range(np_a.shape[1]):
          sum_all = sum_all + np_a[row,col]
          print(f'we are at row={row},col={col} np_a[{row},{col}]={np_a[row,col]} sum_all={sum_all}')
print(sum_all)

we are at row=0,col=0 np_a[0,0]=1 sum_all=1
we are at row=0,col=1 np_a[0,1]=2 sum_all=3
we are at row=0,col=2 np_a[0,2]=3 sum_all=6
we are at row=1,col=0 np_a[1,0]=4 sum_all=10
we are at row=1,col=1 np_a[1,1]=5 sum_all=15
we are at row=1,col=2 np_a[1,2]=6 sum_all=21
21


```np.sum(np_a,axis=0)```

In [87]:
sum_all = np.zeros(np_a.shape[1])

for row in range(np_a.shape[0]):
     for col in range(np_a.shape[1]):
          sum_all[col] = sum_all[col] + np_a[row,col]
print(sum_all)

[5. 7. 9.]


Quiz กลุ่ม

วนลูปหาค่า
* ```np.sum(np_a,axis=1)```
* ```np.mean(np_a)```
* ```np.mean(np_a,axis=0)```
* ```np.mean(np_a,axis=1)```
* ```np.max(np_a)```
* ```np.max(np_a,axis=0)```
* ```np.max(np_a,axis=1)```
* ```np.min(np_a)```
* ```np.min(np_a,axis=0)```
* ```np.min(np_a,axis=1)```

In [88]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
### 10. np.min(np_a,axis=1)
min_row = np.zeros(np_a.shape[0])

for row in range(np_a.shape[0]):
   min_row[row] = min(np_a[row,:])
print(min_row)

TypeError: ignored